
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

const Lato = 'https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&family=Playfair+Display:wght@400;500;600&display=swap'
const YsabeauInfant = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600&family=Ysabeau+Infant:wght@1;100;200;300;400;500;600;700;800;900;1000&display=swap'

export const metadata: Metadata = {
  title: 'Graphy.io',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='overflow-y-hidden'>
      <head>
        <link rel="stylesheet" href={YsabeauInfant} />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
